export const ROUTES = {
  INDEX: '/',
  LOGIN: '/login',
  SEARCH: '/search',
  ABOUT: '/about',
  BOOK: '/book/:id',
  BOOK_SUCCESS: '/book-success',
  FAVORITES: '/favorites',
  CONTACT: '/contact',
  CONTACT_SUCCESS: '/contact-success',
  ACCOMMODATION_DETAILS: '/accommodation/details/:id',
  ACCOMMODATIONS: '/accommodations',
  BLOG: '/blog',
  BLOG_DETAILS: '/blog/:id',
  BLOG_PAGINATION: '/blog/page/:number',
  DASHBOARD: '/dashboard',
  DASHBOARD_MAIN: '/dashboard/:slug',
  DASHBOARD_SUB: '/dashboard/:slug/:slug',
} as const;
